CREATE TABLE accounts (
  id UUID PRIMARY KEY,
  owner_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
  version BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL
);